version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8npass
      POSTGRES_DB: n8n
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - n8n_net

  n8n:
    build:
      context: ./n8n
      dockerfile: Dockerfile
    image: my-custom-n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      # DB settings
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8npass

      # Auth (désactive en dev si besoin)
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=adminpass

      # Timezone
      - GENERIC_TIMEZONE=Europe/Paris
      - TZ=Europe/Paris

      # Pour avoir des webhooks stables
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - WEBHOOK_URL=http://localhost:5678

      # Start msg
      - N8N_RUNNERS_ENABLED=true

    volumes:
      - ./n8n/n8n_data:/home/node/.n8n
      - ./n8n/n8n_shared_data:/data

    depends_on:
      - postgres
    networks:
      - n8n_net

volumes:
  postgres_data:
  n8n_data:

networks:
  n8n_net:
    driver: bridge